<div id="footer">
    Footer
</div>

<div id="copyright">
    Copyright &copy; <?php echo date('Y'); ?>
</div>

</div> <!-- Container Closure -->

<script type="text/javascript" src="/_lib/script/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="/_lib/script/plugins.js"></script>
<script type="text/javascript" src="/_lib/script/functions.js"></script>

</body>
</html>
