<!doctype html>
<!--[if IE 6]> <html lang="en" class="nojs ie6"> <![endif]-->
<!--[if IE 7]> <html lang="en" class="nojs ie7"> <![endif]-->
<!--[if IE 8]> <html lang="en" class="nojs ie8"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" class="nojs"> <!--<![endif]-->

<head>
    <title><?php echo $ttl; ?></title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <!--[if IE]><![endif]-->
    <link rel="stylesheet" type="text/css" media="screen" href="/_lib/css/main.css" />
    <link rel="shortcut icon" href="/favicon.png" />
</head>

<body class="<?php echo 'loc' . $loc[0]; ?>">
<div id="container">

<div id="header">
    Header.
    
    <?php include $_SERVER['DOCUMENT_ROOT'].'/_inc/navmain.inc'; ?>
    
</div>
